-- Retrieve All Customers Who Have Placed Orders

SELECT DISTINCT c.CustomerID, c.FirstName, c.LastName, c.Email

FROM Customers c

JOIN Orders o ON c.CustomerID = o.CustomerID;



-- Retrieve All Customers Who Have Never Placed an Order

SELECT c.CustomerID, c.FirstName, c.LastName, c.Email

FROM Customers c

LEFT JOIN Orders o ON c.CustomerID = o.CustomerID

WHERE o.CustomerID IS NULL;



-- List All Products with Their Category and Supplier Information

SELECT p.ProductID, p.ProductName, c.CategoryName, s.SupplierName, p.Price, p.StockQuantity

FROM Products p

JOIN Categories c ON p.CategoryID = c.CategoryID

JOIN Suppliers s ON p.SupplierID = s.SupplierID;



-- Get Total Sales per Product Category

SELECT c.CategoryName, SUM(od.Quantity * od.UnitPrice) AS TotalSales

FROM OrderDetails od

JOIN Products p ON od.ProductID = p.ProductID

JOIN Categories c ON p.CategoryID = c.CategoryID

GROUP BY c.CategoryName;



-- List the Product Popularity (by Quantity Sold)

SELECT p.ProductName, SUM(od.Quantity) AS TotalQuantitySold

FROM OrderDetails od

JOIN Products p ON od.ProductID = p.ProductID

GROUP BY p.ProductName

ORDER BY TotalQuantitySold DESC;



-- Calculate Average Order Value per Customer

SELECT c.CustomerID, c.FirstName, c.LastName, AVG(o.TotalAmount) AS AverageOrderValue

FROM Customers c

JOIN Orders o ON c.CustomerID = o.CustomerID

GROUP BY c.CustomerID, c.FirstName, c.LastName;



-- List Orders with Total Quantity and Total Price of Products in Each Order

SELECT o.OrderID, SUM(od.Quantity) AS TotalQuantity, SUM(od.Quantity * od.UnitPrice) AS TotalPrice

FROM Orders o

JOIN OrderDetails od ON o.OrderID = od.OrderID

GROUP BY o.OrderID;



-- List All Suppliers with Their Products and the Total Stock Quantity

SELECT s.SupplierID, s.SupplierName, p.ProductName, p.StockQuantity

FROM Suppliers s

JOIN Products p ON s.SupplierID = p.SupplierID

ORDER BY s.SupplierID;



-- Get Total Revenue Generated by Each Supplier

SELECT s.SupplierName, SUM(od.Quantity * od.UnitPrice) AS TotalRevenue

FROM OrderDetails od

JOIN Products p ON od.ProductID = p.ProductID

JOIN Suppliers s ON p.SupplierID = s.SupplierID

GROUP BY s.SupplierName;



-- Find Customers Who Have Placed Orders Exceeding 100 GBP

SELECT c.CustomerID, c.FirstName, c.LastName, SUM(o.TotalAmount) AS TotalSpent

FROM Customers c

JOIN Orders o ON c.CustomerID = o.CustomerID

GROUP BY c.CustomerID, c.FirstName, c.LastName

HAVING SUM(o.TotalAmount) > 100;



-- List Products with Less Than 50 Units in Stock

SELECT p.ProductID, p.ProductName, p.StockQuantity

FROM Products p

WHERE p.StockQuantity < 50;



-- Calculate Average Order Value per Month

SELECT FORMAT(OrderDate, 'yyyy-MM') AS OrderMonth, AVG(TotalAmount) AS AverageOrderValue

FROM Orders

GROUP BY FORMAT(OrderDate, 'yyyy-MM')

ORDER BY OrderMonth;



-- List All Products Sold in a Specific Month

SELECT o.OrderDate, p.ProductID, p.ProductName, SUM(od.Quantity) AS TotalQuantitySold

FROM OrderDetails od

JOIN Orders o ON od.OrderID = o.OrderID

JOIN Products p ON od.ProductID = p.ProductID

WHERE FORMAT(o.OrderDate, 'yyyy-MM') = '2023-01'

GROUP BY o.OrderDate, p.ProductID, p.ProductName

ORDER BY o.OrderDate, p.ProductID;



-- Calculate the Total Number of Orders Placed by Each Customer

SELECT c.CustomerID, c.FirstName, c.LastName, COUNT(o.OrderID) AS TotalOrders

FROM Customers c

JOIN Orders o ON c.CustomerID = o.CustomerID

GROUP BY c.CustomerID, c.FirstName, c.LastName;

